apiVersion: v1
kind: Service
metadata:
  name: toncountymuseum
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "toncountymuseum"
    port: 8080
  selector:
    app: toncountymuseum
